@fleetops_backend_HostAddress = http://localhost:5107

### Login
POST {{fleetops_backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "user555",
  "password": "wkwkwkwk"
}

### Register
POST {{fleetops_backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Fit",
  "email": "wkwk@gmail.com",
  "password": "wkwkwkwk"
}