// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fleetops_backend.Infrastructure.Data;

#nullable disable

namespace fleetops_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505123443_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fleetops_backend.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverId"));

                    b.Property<string>("JenisLisensi")
                        .HasColumnType("text")
                        .HasColumnName("jenis_lisensi");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("TanggalBerlaku")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal_berlaku");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("DriverId")
                        .HasName("pk_drivers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_user_id");

                    b.ToTable("drivers", (string)null);

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            JenisLisensi = "B",
                            Status = "Active",
                            TanggalBerlaku = new DateTimeOffset(new DateTime(2031, 5, 2, 11, 59, 13, 649, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int>("HargaLiter")
                        .HasColumnType("integer")
                        .HasColumnName("harga_liter");

                    b.Property<int>("HargaTotal")
                        .HasColumnType("integer")
                        .HasColumnName("harga_total");

                    b.Property<string>("ImageUrlPath")
                        .HasColumnType("text")
                        .HasColumnName("image_url_path");

                    b.Property<int>("JmlLiter")
                        .HasColumnType("integer")
                        .HasColumnName("jml_liter");

                    b.Property<string>("LokasiPengisian")
                        .HasColumnType("text")
                        .HasColumnName("lokasi_pengisian");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_fuels");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_fuels_driver_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_fuels_vehicle_id");

                    b.ToTable("fuels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 2, 11, 59, 13, 651, DateTimeKind.Utc),
                            DriverId = 1,
                            HargaLiter = 15000,
                            HargaTotal = 750000,
                            JmlLiter = 50,
                            LokasiPengisian = "Jakarta Pusat",
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_inspections");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_inspections_driver_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_inspections_trip_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_inspections_vehicle_id");

                    b.ToTable("inspections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 2, 11, 59, 13, 652, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DriverId = 1,
                            Status = true,
                            TripId = 1,
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_inspection_items");

                    b.ToTable("inspection_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsRequired = true,
                            Name = "Brake Condition"
                        },
                        new
                        {
                            Id = 2,
                            IsRequired = true,
                            Name = "Tire Condition"
                        },
                        new
                        {
                            Id = 3,
                            IsRequired = true,
                            Name = "Lights"
                        },
                        new
                        {
                            Id = 4,
                            IsRequired = false,
                            Name = "Mirrors"
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrlPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url_path");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.HasKey("Id")
                        .HasName("pk_inspection_photos");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_inspection_photos_inspection_id");

                    b.ToTable("inspection_photos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrlPath = "https://example.com/photo1.jpg",
                            InspectionId = 1,
                            IsRequired = true
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Condition")
                        .HasColumnType("integer")
                        .HasColumnName("condition");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    b.HasKey("Id")
                        .HasName("pk_inspection_results");

                    b.HasIndex("InspectionId")
                        .HasDatabaseName("ix_inspection_results_inspection_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inspection_results_item_id");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("ix_inspection_results_photo_id");

                    b.ToTable("inspection_results", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condition = 1,
                            InspectionId = 1,
                            ItemId = 1,
                            Note = "Brake pads good condition",
                            PhotoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Condition = 1,
                            InspectionId = 1,
                            ItemId = 2,
                            Note = "Tires properly inflated"
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Biaya")
                        .HasColumnType("numeric")
                        .HasColumnName("biaya");

                    b.Property<string>("Catatan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catatan");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Odometer")
                        .HasColumnType("integer")
                        .HasColumnName("odometer");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tanggal");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_maintenances");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_maintenances_vehicle_id");

                    b.ToTable("maintenances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biaya = 500000m,
                            Catatan = "Rutin maintenance check",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 2, 11, 59, 13, 651, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Odometer = 5000,
                            Tanggal = new DateTime(2026, 5, 2, 11, 59, 13, 651, DateTimeKind.Utc),
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FleetManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Driver"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Unassigned"
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<string>("Catatan")
                        .HasColumnType("text")
                        .HasColumnName("catatan");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<double?>("JarakTempuh")
                        .HasColumnType("double precision")
                        .HasColumnName("jarak_tempuh");

                    b.Property<Point>("KordAkhir")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("kord_akhir");

                    b.Property<Point>("KordAwal")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("kord_awal");

                    b.Property<string>("LokasiAkhir")
                        .HasColumnType("text")
                        .HasColumnName("lokasi_akhir");

                    b.Property<string>("LokasiAwal")
                        .HasColumnType("text")
                        .HasColumnName("lokasi_awal");

                    b.Property<double?>("OdometerAkhir")
                        .HasColumnType("double precision")
                        .HasColumnName("odometer_akhir");

                    b.Property<double?>("OdometerAwal")
                        .HasColumnType("double precision")
                        .HasColumnName("odometer_awal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<DateTimeOffset>("WaktuMulai")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waktu_mulai");

                    b.Property<DateTimeOffset?>("WaktuSelesai")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waktu_selesai");

                    b.HasKey("TripId")
                        .HasName("pk_trips");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_trips_driver_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_trips_vehicle_id");

                    b.ToTable("trips", (string)null);

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            Catatan = "Trip completed successfully",
                            DriverId = 1,
                            JarakTempuh = 150.0,
                            LokasiAkhir = "Bandung",
                            LokasiAwal = "Jakarta",
                            OdometerAkhir = 1150.5,
                            OdometerAwal = 1000.5,
                            Status = "Completed",
                            VehicleId = 1,
                            WaktuMulai = new DateTimeOffset(new DateTime(2026, 5, 2, 9, 59, 13, 650, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WaktuSelesai = new DateTimeOffset(new DateTime(2026, 5, 2, 11, 59, 13, 650, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.TripDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("avg_speed");

                    b.Property<string>("DriverImageUrlPath")
                        .HasColumnType("text")
                        .HasColumnName("driver_image_url_path");

                    b.Property<string>("ItemImageUrlPath")
                        .HasColumnType("text")
                        .HasColumnName("item_image_url_path");

                    b.Property<int>("Jarak")
                        .HasColumnType("integer")
                        .HasColumnName("jarak");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<int>("Waktu")
                        .HasColumnType("integer")
                        .HasColumnName("waktu");

                    b.HasKey("Id")
                        .HasName("pk_trip_details");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_details_trip_id");

                    b.ToTable("trip_details", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgSpeed = 75,
                            DriverImageUrlPath = "https://example.com/driver-image.jpg",
                            ItemImageUrlPath = "https://example.com/item-image.jpg",
                            Jarak = 150,
                            TripId = 1,
                            Waktu = 7200
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 2, 11, 59, 13, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "driver@fleetops.local",
                            FullName = "FleetOps Test Driver",
                            PasswordHash = "$2a$11$wvBoSd9TRmWoarbcfmSrwu.AeqYvmWSP1o.fdUrj88yS33TSJL2Dm",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int>("MaintenanceIntervalDay")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_interval_day");

                    b.Property<int>("MaintenanceIntervalKm")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_interval_km");

                    b.Property<int>("Odometer")
                        .HasColumnType("integer")
                        .HasColumnName("odometer");

                    b.Property<string>("PLatNomor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p_lat_nomor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipe");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_name");

                    b.HasKey("VehicleId")
                        .HasName("pk_vehicles");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_vehicles_driver_id");

                    b.ToTable("vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            DriverId = 1,
                            MaintenanceIntervalDay = 90,
                            MaintenanceIntervalKm = 5000,
                            Odometer = 0,
                            PLatNomor = "B 1234 ABC",
                            Status = "Active",
                            Tipe = "Truck",
                            VehicleName = "Truck-001"
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Driver", b =>
                {
                    b.HasOne("fleetops_backend.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("fleetops_backend.Models.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_drivers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("fleetops_backend.Models.Fuel", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Fuel")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_fuels_drivers_driver_id");

                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Fuel")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fuels_vehicles_vehicle_id");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.Inspection", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Inspection")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspections_drivers_driver_id");

                    b.HasOne("fleetops_backend.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspections_trips_trip_id");

                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Inspection")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspections_vehicles_vehicle_id");

                    b.Navigation("Driver");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionPhoto", b =>
                {
                    b.HasOne("fleetops_backend.Models.Inspection", "Inspection")
                        .WithMany("Photos")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_photos_inspections_inspection_id");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionResult", b =>
                {
                    b.HasOne("fleetops_backend.Models.Inspection", "Inspection")
                        .WithMany("Results")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_results_inspections_inspection_id");

                    b.HasOne("fleetops_backend.Models.InspectionItem", "Item")
                        .WithMany("Result")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_results_inspection_items_item_id");

                    b.HasOne("fleetops_backend.Models.InspectionPhoto", "Photo")
                        .WithMany("Result")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inspection_results_inspection_photos_photo_id");

                    b.Navigation("Inspection");

                    b.Navigation("Item");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("fleetops_backend.Models.Maintenance", b =>
                {
                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Maintenance")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenances_vehicles_vehicle_id");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.Trip", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Trip")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_drivers_driver_id");

                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Trip")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_vehicles_vehicle_id");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.TripDetail", b =>
                {
                    b.HasOne("fleetops_backend.Models.Trip", "Trip")
                        .WithMany("Detail")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_details_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("fleetops_backend.Models.User", b =>
                {
                    b.HasOne("fleetops_backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("fleetops_backend.Models.Vehicle", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Vehicle")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("fleetops_backend.Models.Driver", b =>
                {
                    b.Navigation("Fuel");

                    b.Navigation("Inspection");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.Inspection", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionItem", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionPhoto", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("fleetops_backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("fleetops_backend.Models.Trip", b =>
                {
                    b.Navigation("Detail");
                });

            modelBuilder.Entity("fleetops_backend.Models.Vehicle", b =>
                {
                    b.Navigation("Fuel");

                    b.Navigation("Inspection");

                    b.Navigation("Maintenance");

                    b.Navigation("Trip");
                });
#pragma warning restore 612, 618
        }
    }
}
