// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fleetops_backend.Infrastructure.Data;

#nullable disable

namespace fleetops_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fleetops_backend.Models.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverId"));

                    b.Property<string>("JenisLisensi")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TanggalBerlaku")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("DriverId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("fleetops_backend.Models.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int>("HargaLiter")
                        .HasColumnType("integer");

                    b.Property<int>("HargaTotal")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrlPath")
                        .HasColumnType("text");

                    b.Property<int>("JmlLiter")
                        .HasColumnType("integer");

                    b.Property<string>("LokasiPengisian")
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Fuels");
                });

            modelBuilder.Entity("fleetops_backend.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TripId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InspectionItems");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrlPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("InspectionPhotos");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<int>("InspectionId")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PhotoId");

                    b.ToTable("InspectionResults");
                });

            modelBuilder.Entity("fleetops_backend.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Biaya")
                        .HasColumnType("numeric");

                    b.Property<string>("Catatan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Odometer")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("fleetops_backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FleetManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Driver"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Unassigned"
                        });
                });

            modelBuilder.Entity("fleetops_backend.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<Point>("KordAkhir")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("kord_akhir");

                    b.Property<Point>("KordAwal")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("kord_awal");

                    b.Property<string>("LokasiAkhir")
                        .HasColumnType("text");

                    b.Property<string>("LokasiAwal")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<DateTimeOffset>("WaktuMulai")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waktu_mulai");

                    b.Property<DateTimeOffset?>("WaktuSelesai")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waktu_selesai");

                    b.HasKey("TripId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("fleetops_backend.Models.TripDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrlPath")
                        .HasColumnType("text");

                    b.Property<int>("Jarak")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<int>("Waktu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripDetails");
                });

            modelBuilder.Entity("fleetops_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("fleetops_backend.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int>("MaintenanceIntervalDay")
                        .HasColumnType("integer");

                    b.Property<int>("MaintenanceIntervalKm")
                        .HasColumnType("integer");

                    b.Property<int>("Odometer")
                        .HasColumnType("integer");

                    b.Property<string>("PLatNomor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleId");

                    b.HasIndex("DriverId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("fleetops_backend.Models.Driver", b =>
                {
                    b.HasOne("fleetops_backend.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("fleetops_backend.Models.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fleetops_backend.Models.Fuel", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Fuel")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Fuel")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.Inspection", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Inspection")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fleetops_backend.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Inspection")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionPhoto", b =>
                {
                    b.HasOne("fleetops_backend.Models.Inspection", "Inspection")
                        .WithMany("Photos")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionResult", b =>
                {
                    b.HasOne("fleetops_backend.Models.Inspection", "Inspection")
                        .WithMany("Results")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fleetops_backend.Models.InspectionItem", "Item")
                        .WithMany("Result")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fleetops_backend.Models.InspectionPhoto", "Photo")
                        .WithMany("Result")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Inspection");

                    b.Navigation("Item");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("fleetops_backend.Models.Maintenance", b =>
                {
                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Maintenance")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.Trip", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Trip")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fleetops_backend.Models.Vehicle", "Vehicle")
                        .WithMany("Trip")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.TripDetail", b =>
                {
                    b.HasOne("fleetops_backend.Models.Trip", "Trip")
                        .WithMany("Detail")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("fleetops_backend.Models.User", b =>
                {
                    b.HasOne("fleetops_backend.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("fleetops_backend.Models.Vehicle", b =>
                {
                    b.HasOne("fleetops_backend.Models.Driver", "Driver")
                        .WithMany("Vehicle")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("fleetops_backend.Models.Driver", b =>
                {
                    b.Navigation("Fuel");

                    b.Navigation("Inspection");

                    b.Navigation("Trip");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("fleetops_backend.Models.Inspection", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionItem", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("fleetops_backend.Models.InspectionPhoto", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("fleetops_backend.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("fleetops_backend.Models.Trip", b =>
                {
                    b.Navigation("Detail");
                });

            modelBuilder.Entity("fleetops_backend.Models.Vehicle", b =>
                {
                    b.Navigation("Fuel");

                    b.Navigation("Inspection");

                    b.Navigation("Maintenance");

                    b.Navigation("Trip");
                });
#pragma warning restore 612, 618
        }
    }
}
